[project]
name = 'covered-call'
description = 'This contract allows for the creation, transfer, exercise, and underlying reclamation needed for covered calls'
authors = ['Rafa']
telemetry = true
cache_dir = '.cache'
requirements = []
[contracts.covered-call]
path = 'contracts/covered-call.clar'
clarity_version = 1
epoch = 2.0

[contracts.bitcoin-call]
path = 'contracts/bitcoin-call.clar'
clarity_version = 1
epoch = 2.0

[contracts.sbtc]
path = 'contracts/sbtc.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip009-nft-trait]
path = 'contracts/sip009-nft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip010-ft-trait]
path = 'contracts/sip010-ft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.wrapped-usdc]
path = 'contracts/wrapped-usdc.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
